site_name: Keiron's Documentation Portal
site_url: https://docs.keiron.xyz
repo_url: https://github.com/KeironO/docs
copyright: Copyright &copy; 2023 Keiron O'Shea
theme:
  name: 'material'
  palette:
    primary: black
  features:
    - navigation.indexes
    - navigation.sections
    - search.highlight
    - search.share
  font:
    text: 'Inter'


markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - def_list
  - pymdownx.tasklist:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - glightbox

extra_css:
  - stylesheets/extra.css
