site_name: Keiron's Documentation Portal
site_url: https://docs.keiron.xyz
repo_url: https://github.com/KeironO/docs
theme:
  name: 'material'
  font:
    text: 'Inter'
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - mdx_include:
      base_path: docs
  - attr_list
  - md_in_html

plugins:
  - search
  - minify:
      minify_html: true
  - glightbox

extra_css:
  - stylesheets/extra.css
